mysite/home/urls.py
from django.urls import path

from .views import home_view

app_name = "home"

urlpatterns = (
    path("", home_view, name="home-page"),
)

mysite/myauth/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import (
    get_cookie_view,
    set_cookie_view,
    set_session_view,
    get_session_view,
    MyLogoutView,
    AboutMeView,
    RegisterView,
    start_auth_view,
    FooBarView,
    ProfileListView,
    AboutMeDetailView,
    ProfileAvatarUpdateView,
    HelloView,
)

app_name = "myauth"

urlpatterns = (
    path("", start_auth_view, name="start"),
    # path("login/", login_view, name="login"),
    path(
        "login/",
        LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True
        ),
        name="login"),
    path("hello/", HelloView.as_view(), name='hello'),
    path("reg/", RegisterView.as_view(), name='register'),
    path("profiles-list/", ProfileListView.as_view(), name='profiles-list'),
    path("about-me/", AboutMeView.as_view(), name='about-me'),
    path("about-me-details/<int:pk>/", AboutMeDetailView.as_view(), name='about-me-details'),
    path("about-me-details/<int:pk>/update", ProfileAvatarUpdateView.as_view(), name='update-avatar'),
    # path("logout/", MyLogoutView.as_view(), name='logout'),
    path("logout/", LogoutView.as_view(), name='logout'),

    path("cookie/get/", get_cookie_view, name='cookie-get'),
    path("cookie/set/", set_cookie_view, name='cookie-set'),

    path("session/set/", set_session_view, name='session-set'),
    path("session/get/", get_session_view, name='session-get'),

    path("foo-bar", FooBarView.as_view(), name='foo-bar'),
)

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from .sitemaps import sitemaps
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('req/', include('requestdataapp.urls')),
    path('blog/', include('blogapp.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name="schema"),
    path('api/schema/svagger', SpectacularSwaggerView.as_view(url_name='schema'), name="svagger"),
    path('api/schema/redoc', SpectacularRedocView.as_view(url_name='schema'), name="redoc"),
    path('api/', include('myapiapp.urls')),
    path(
        'sitemap.xml',
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap"
    )
]

urlpatterns += i18n_patterns(
    path('accounts/', include('myauth.urls')),
    path('shop/', include('shopapp.urls')),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

mysite/requestdataapp/urls.py
from django.urls import path
from .views import process_det_view, user_form, handel_file_uploap

app_name = "requestdataapp"

urlpatterns = [
    path("get/", process_det_view, name="get-vew"),
    path("bio/", user_form, name="user-form"),
    path("upload/",handel_file_uploap , name="file-upload"),
]

mysite/shopapp/urls.py
from tempfile import template
from django.contrib.auth.views import LoginView
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from django.views.decorators.cache import cache_page

from .views import (
    ShopIndexView,
    GroupsListView,
    ProductDetailsView,
    ProductsListView,
    OrdersListViev,
    OrdersDetailViev,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    ProductsDataExportView,
    OrderUpdateView,
    OrderCreateView,
    OrderDeleteView,
    user_orders_export,
    api_hello_view,
    ProductViewSet,
    OrderViewSet,
    LatestProductsFeed,
    UserOrdersListView,

)

app_name = "shopapp"

routers = DefaultRouter()
routers.register("products", ProductViewSet)
routers.register("orders", OrderViewSet)

urlpatterns = [
    # path("", cache_page(60*3)(ShopIndexView.as_view()), name='index'),
    path("", ShopIndexView.as_view(), name='index'),
    path("groups/", GroupsListView.as_view(), name='groups_list'),
    path("products/", ProductsListView.as_view(), name='products_list'),
    path("products/feed", LatestProductsFeed(), name='products_feed'),
    path("products/export", ProductsDataExportView.as_view(), name='products_export'),
    path("products/create/", ProductCreateView.as_view(), name='product_create'),
    path("products/<int:pk>/", ProductDetailsView.as_view(), name='product_details'),
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name='product_update'),
    path("products/<int:pk>/archive/", ProductDeleteView.as_view(), name='product_archive'),
    path("orders/", OrdersListViev.as_view(), name='orders_list'),
    path("user-orders/<int:user_id>/", UserOrdersListView.as_view(), name='user_orders_list'),
    path("orders/<int:user_id>/export", user_orders_export, name='orders_export'),
    path("orders/create/", OrderCreateView.as_view(), name='create_order'),
    path("orders/<int:pk>/", OrdersDetailViev.as_view(), name='order_details'),
    path("orders/<int:pk>/update", OrderUpdateView.as_view(), name='order_update'),
    path("orders/<int:pk>/confirm_delete/", OrderDeleteView.as_view(), name='order_delete'),
    path("api/", include(routers.urls)),
]

mysite/myauth/models.py
from django.contrib.auth.models import User
import os
from django.db import models
from django.conf import settings
from django.utils.deconstruct import deconstructible
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from django.core.files.uploadedfile import UploadedFile
from django.core.files import File


@deconstructible
class ProfileAvatarDirectoryPath:
    def __call__(self, instance, filename):
        return "profiles/profiles_{pk}/avatar/{filename}".format(
            pk=instance.pk,
            filename=filename,
        )

profile_avatar_directory_path = ProfileAvatarDirectoryPath()

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    agreement_accepted = models.BooleanField(default=False)
    avatar = models.ImageField(
        null=True,
        blank=True,
        upload_to=profile_avatar_directory_path)

    _avatar_pending = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._avatar_pending = None
        self.old_avatar = None

    def save(self, *args, **kwargs):
        is_new = not self.pk
        if is_new:
            super().save(*args, **kwargs)

        if self.avatar and self._avatar_pending is None:
            self._avatar_pending = self.avatar
            self.avatar = None

        if self._avatar_pending:
            file_path = profile_avatar_directory_path(self, os.path.basename(self._avatar_pending.name))

            if isinstance(self._avatar_pending, File):
                file_content = self._avatar_pending.read()
            elif isinstance(self._avatar_pending, str) and default_storage.exists(self._avatar_pending):
                file_content = default_storage.open(self._avatar_pending, 'rb').read()
            else:
                self._avatar_pending = None
                return

            if isinstance(self._avatar_pending, File):
                new_file_path = default_storage.save(file_path, self._avatar_pending)
            else:
                new_file_path = default_storage.save(file_path, default_storage.open(self._avatar_pending, 'rb'))

            self.avatar = new_file_path
            self._avatar_pending = None

        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return f"Profile(pk={self.pk}, name={self.user.username!r})"

mysite/myauth/forms.py
from django.contrib.auth.models import Group
from django import forms
from django.forms import ModelForm
from django.core import validators
from .models import Profile

class ProfileForm(ModelForm):
    class Meta():
        model = Profile
        fields = ("avatar",)

mysite/myauth/views.py
from random import random
from http.client import responses
from itertools import product
from pkgutil import resolve_name
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LogoutView
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.template.context_processors import request
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView, CreateView, DeleteView, UpdateView
from .models import Profile
from .forms import ProfileForm
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _, gettext as __, ngettext_lazy
from django.views.decorators.cache import cache_page

import logging


def start_auth_view(request: HttpRequest):
    return render(request, "myauth/login.html")

class AboutMeView(TemplateView):
    template_name = "myauth/about-me.html"
    # model = Product
    queryset = Profile.objects.all()
    context_object_name = "profile"

class AboutMeDetailView(DetailView):
    template_name = "myauth/about-me-details.html"
    # model = Product
    queryset = Profile.objects.all()
    context_object_name = "profile"

class ProfileAvatarUpdateView(UserPassesTestMixin, UpdateView):
    model = Profile
    def test_func(self):
        profile = self.get_object()
        logging.warning(f"{profile.user_id}, {self.request.user.id}")
        if self.request.user.is_superuser:
            return True
        elif profile.user_id == self.request.user.id:
            return True
#     fields = "name", "description", "price", "discount", "preview"
    form_class = ProfileForm
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse(
            "myauth:about-me-details",
            kwargs={"pk": self.object.pk},
        )


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = "myauth/register.html"
    success_url = reverse_lazy("myauth:about-me")

    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)

        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user = authenticate(
            self.request,
            username=username,
            password=password
        )
        login(request=self.request, user=user)
        return response

class MyLogoutView(LogoutView):
    next_page = reverse_lazy("myauth:login")

@user_passes_test(lambda u: u.is_superuser)
def set_cookie_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse("Cookie set")
    response.set_cookie("fizz", "buzz", max_age=3600)
    return response

@cache_page(60 * 2)
def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get("fizz", "default value")
    return HttpResponse(f"Cookie value: {value!r} + {random()}")

@permission_required("myauth.view_profile")
def set_session_view(request: HttpRequest) -> HttpResponse:
    request.session["foobar"] = "spameggs"
    return HttpResponse("Session set")

@login_required
def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get("foobar", "default")
    return HttpResponse(f"Session value: {value!r}")

class FooBarView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
          return JsonResponse({'foo': 'bar', 'spam': 'eggs'})

class ProfileListView(ListView):
    template_name = 'myauth/profiles-list.html'
    # model = Profile
    context_object_name = "profiles"
    queryset = Profile.objects.all

class HelloView(View):
    welcome_message = _("welcome hello world")

    def get(self, request: HttpRequest) -> HttpResponse:
        items_str = request.GET("items") or 0
        items = int(items_str)
        products_line = ngettext_lazy(
            "one product",
            "{count} products",
            items,
        )
        products_line = products_line.format(count=items)
        return HttpResponse(
            f"<h1>{self.welcome_message}</h1>"
            f"\n<h2>{products_line}</h2>"
        )







""" ____________________________________________________________________________________
Самодельная View функция для Входа """

# def login_view(request: HttpRequest):
#     if request.method == "GET":
#         if request.user.is_authenticated:
#             return redirect('/admin/')
#
#         return render(request, 'shopapp/login.html')
#
#     username = request.POST['username']
#     password = request.POST['password']
#
#     user = authenticate(request, username=username, password=password)
#     if user:
#         login(request, user)
#         return redirect('/admin/')
#
#     return render(request, "shopapp/login.html", {"error": "Неверные значения"})
"""______________________________________________________________________
Самодельная View функция для Logout"""

# def logout_view(request: HttpRequest) -> HttpResponse:
#     logout(request)
#     return redirect(reverse("shopapp:login"))
"""______________________________________________________________________"""

mysite/myauth/templates/myauth/about-me-details.html
{% extends 'myauth/baseauth.html' %}

{% block title %}
    Обо мне
{% endblock %}

{% block body %}
    <div>
        <h1>Информация о пользователе</h1>
        {% if user.is_authenticated %}
            {% if profile.avatar %}
                <img src="{{ user.profile.avatar.url }}" alt="{{ user.profile.avatar.name }}" style="height: 200px; width: 180px">
            {% endif %}
            <p>Ник пользователя: {{ profile.user.username }}</p>
            <p>Имя пользователя: {{ profile.user.first_name }}</p>
            <p>Фамилия пользователя: {{ profile.user.last_name }}</p>
            <p>Email: {{ profile.user.email }}</p>
            <p>Bio: {{ user.profile.bio }}</p>
        {% else %}
            <h2>Пользователь анонимен</h2>
        {% endif %}

        {% if profile.user_id == user.pk and user.is_staff %}
            <div>
                <a href="{% url 'myauth:update-avatar' pk=profile.pk %}">Обновить аватар</a>
            </div>
        {% endif %}
        <div>
        <a href="{% url 'myauth:profiles-list' %}">К списку профилей</a>
        </div>
    </div>


{% endblock %}

mysite/myauth/templates/myauth/about-me.html
{% extends 'myauth/baseauth.html' %}
{% load cache %}

{% block title %}
    Обо мне
{% endblock %}

{% block body %}
    <div>
        <h1>Информация о пользователе</h1>
        <div>
            {% now "u" %}
        </div>
        {% if user.is_authenticated %}
            {% cache 300 userinfo user.username %}
            {% if profile.avatar %}
                <img src="{{ user.profile.avatar.url }}" alt="{{ user.profile.avatar.name }}" style="height: 200px; width: 180px">
            {% endif %}
            <p>Ник пользователя: {{ user.username }}</p>
            <p>Имя пользователя: {{ user.first_name }}</p>
            <p>Фамилия пользователя: {{ user.last_name }}</p>
            <p>Email: {{ user.email }}</p>
            <p>Bio: {{ user.profile.bio }}</p>
            <div>
            {% now "u" %}
            </div>
            {% endcache %}
        {% else %}
            <h2>Пользователь анонимен</h2>
        {% endif %}
    </div>


{% endblock %}

mysite/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
      {% block title %}
       Base Title
      {% endblock %}
    </title>
</head>
<body>

{% block body %}
 Base Body
{% endblock %}

  <div>
    {% now 'H:i" %}
  </div>

  <div>
    {% now 'l' as current_weekday %}
    Today is {{ current_weekday }}
  </div>

</body>
</html>

mysite/myauth/templates/myauth/baseauth.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
      {% block title %}
       Base Title
      {% endblock %}
    </title>

    <style>

      * {
        font-family: 'Roboto', sans-serif;
      }

      html, body {
        color: white;
        background-color: #f6f7f9;
        margin: 0;
        padding: 0;
      }

      header {
        color: white;
        padding: 20px 0px;
        background-color: #271d3e;
      }

      header > div {
        display: flex;
        justify-content: space-between;
        align-items: center;
      }

      .head-container {
        max-width: 1000px;
        height: 100%;
        margin-left: auto;
        margin-right: auto;
      }

      .head-container a{
        text-decoration: none;
        color: rgb(226, 77, 147);
      }

      .block {
        width: 100%;
        display: flex;
      }

      .block a {
        text-decoration: none;
        color: rgb(168, 73, 117);
      }


      .left-contein {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: space-between;
        /* background-color: aqua; */
        height: 100vh;
        width: 250px;
        padding: 10px;
        background-color: #271d3e;
        
      }

      .main-contein {
        text-align: center;
        background-color: rgb(70, 58, 97);
        width: 100%;
        padding: 20px;
        border-top: 1px solid black;
        border-left: 1px solid black;
        /* background-image: url('C:/Users/mrnif/Pictures/фоны/main.png');
        background-size: contain;
        background-repeat: no-repeat;
        background-position: right center; */
      }

      .navigate {
        display: flex;
        flex-direction: column;
        align-items: center;
      }

    </style>
</head>



<body>
    
  <header>
    <div class="head-container">
        <a href="{% url 'shopapp:index' %}">shopapp</a>
        <a href="{% url 'myauth:login' %}">auth</a>
        <a href="{% url 'requestdataapp:get-vew' %}">requestdataapp</a>
        <a href="{% url 'home:home-page' %}">home</a>
        <a href="{% url 'myauth:logout' %}" style="color: red">Выход</a>
    </div>
  </header>

  <section class="block">
    <div class="left-contein">
      <div class="navigate">
      
        <h2 style="border: 1px solid black; 
        border-radius: 40px; 
        padding: 20px;
        background-color: #2d0d79;"
        >Навигация</h2>

        <div style="margin-top: 60px ;">
          <p><a href="{% url 'myauth:register' %}">Регистрация</a></p>
          <p><a href="{% url 'myauth:profiles-list' %}">Список пользователей</a></p>
          <p><a href="{% url 'myauth:about-me' %}">Обо мне</a></p>
          <div>
            <h3>Cookie</h3>
            <p><a href="{% url 'myauth:cookie-get' %}">Get</a></p>
            <p><a href="{% url 'myauth:cookie-set' %}">Set</a></p>
          </div>
          <div>
            <h3>Session</h3>
            <p><a href="{% url 'myauth:session-get' %}">Get</a></p>
            <p><a href="{% url 'myauth:session-set' %}">Set</a></p>
          </div>
        </div>

      </div>

      <div class="detail">
        <div>
          {% now 'H:i" %}
        </div>
  
        <div>
          {% now 'l' as current_weekday %}
          Today is {{ current_weekday }}
        </div>
      </div>
      

    </div>

    <div class="main-contein">
      {% block body %}
      Base Body
      {% endblock %}
    </div>

  </section>

  <footer>

  </footer>

</body>
</html>

mysite/myauth/templates/myauth/login.html
{% extends 'myauth/baseauth.html' %}

{% block title %}
    Вход
{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Войти</button>
    </form>
{% endblock %}

mysite/myauth/templates/myauth/profile_update_form.html
{% extends 'myauth/baseauth.html' %}

{% block title %}
    Обновление аватарки
{% endblock %}

{% block body %}
    <div>Обновление аватарки</div>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Обновить</button>
        </form>
    </div>
    <div>
        <a href="{% url 'myauth:about-me-details' pk=profile.pk %}"
        >Вернуться к деталям</a>
    </div>
{% endblock %}

mysite/myauth/templates/myauth/profiles-list.html
{% extends 'myauth/baseauth.html' %}

{% block title %}
    Список профилей
{% endblock %}

{% block body %}

    <h1>Профили</h1>
        {% if profiles %}
            <div>

            {% for profile in profiles %}
                <div>
                    {% if profile.avatar %}
                        <img src="{{ user.profile.avatar.url }}" alt="{{ user.profile.avatar.name }}" style="height: 200px; width: 180px">
                    {% endif %}
                    <p>Name: <a href="{% url 'myauth:about-me-details' pk=profile.pk %}">{{ profile.user.username }}</a></p>
                    <p>Описание: {% firstof profile.bio 'Нет описания'%}</p>

                </div>
            {% endfor %}

            </div>

        {% else %}
            <h3>Нет профилей</h3>
        {% endif %}

{% endblock %}

mysite/myauth/templates/myauth/register.html
{% extends 'myauth/baseauth.html' %}

{% block title %}
    Регистрация
{% endblock %}

{% block body %}
    <h1>Регистрация</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
            <input type="submit" value="Регистрация">
    </form>
{% endblock %}