mysite/home/urls.py
from django.urls import path

from .views import home_view

app_name = "home"

urlpatterns = (
    path("", home_view, name="home-page"),
)

mysite/myauth/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import (
    get_cookie_view,
    set_cookie_view,
    set_session_view,
    get_session_view,
    MyLogoutView,
    AboutMeView,
    RegisterView,
    start_auth_view,
    FooBarView,
    ProfileListView,
    AboutMeDetailView,
    ProfileAvatarUpdateView,
    HelloView,
)

app_name = "myauth"

urlpatterns = (
    path("", start_auth_view, name="start"),
    # path("login/", login_view, name="login"),
    path(
        "login/",
        LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True
        ),
        name="login"),
    path("hello/", HelloView.as_view(), name='hello'),
    path("reg/", RegisterView.as_view(), name='register'),
    path("profiles-list/", ProfileListView.as_view(), name='profiles-list'),
    path("about-me/", AboutMeView.as_view(), name='about-me'),
    path("about-me-details/<int:pk>/", AboutMeDetailView.as_view(), name='about-me-details'),
    path("about-me-details/<int:pk>/update", ProfileAvatarUpdateView.as_view(), name='update-avatar'),
    # path("logout/", MyLogoutView.as_view(), name='logout'),
    path("logout/", LogoutView.as_view(), name='logout'),

    path("cookie/get/", get_cookie_view, name='cookie-get'),
    path("cookie/set/", set_cookie_view, name='cookie-set'),

    path("session/set/", set_session_view, name='session-set'),
    path("session/get/", get_session_view, name='session-get'),

    path("foo-bar", FooBarView.as_view(), name='foo-bar'),
)

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from .sitemaps import sitemaps
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('req/', include('requestdataapp.urls')),
    path('blog/', include('blogapp.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name="schema"),
    path('api/schema/svagger', SpectacularSwaggerView.as_view(url_name='schema'), name="svagger"),
    path('api/schema/redoc', SpectacularRedocView.as_view(url_name='schema'), name="redoc"),
    path('api/', include('myapiapp.urls')),
    path(
        'sitemap.xml',
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap"
    )
]

urlpatterns += i18n_patterns(
    path('accounts/', include('myauth.urls')),
    path('shop/', include('shopapp.urls')),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

mysite/requestdataapp/urls.py
from django.urls import path
from .views import process_det_view, user_form, handel_file_uploap

app_name = "requestdataapp"

urlpatterns = [
    path("get/", process_det_view, name="get-vew"),
    path("bio/", user_form, name="user-form"),
    path("upload/",handel_file_uploap , name="file-upload"),
]

mysite/shopapp/urls.py
from tempfile import template
from django.contrib.auth.views import LoginView
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from django.views.decorators.cache import cache_page

from .views import (
    ShopIndexView,
    GroupsListView,
    ProductDetailsView,
    ProductsListView,
    OrdersListViev,
    OrdersDetailViev,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    ProductsDataExportView,
    OrderUpdateView,
    OrderCreateView,
    OrderDeleteView,
    user_orders_export,
    api_hello_view,
    ProductViewSet,
    OrderViewSet,
    LatestProductsFeed,
    UserOrdersListView,

)

app_name = "shopapp"

routers = DefaultRouter()
routers.register("products", ProductViewSet)
routers.register("orders", OrderViewSet)

urlpatterns = [
    # path("", cache_page(60*3)(ShopIndexView.as_view()), name='index'),
    path("", ShopIndexView.as_view(), name='index'),
    path("groups/", GroupsListView.as_view(), name='groups_list'),
    path("products/", ProductsListView.as_view(), name='products_list'),
    path("products/feed", LatestProductsFeed(), name='products_feed'),
    path("products/export", ProductsDataExportView.as_view(), name='products_export'),
    path("products/create/", ProductCreateView.as_view(), name='product_create'),
    path("products/<int:pk>/", ProductDetailsView.as_view(), name='product_details'),
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name='product_update'),
    path("products/<int:pk>/archive/", ProductDeleteView.as_view(), name='product_archive'),
    path("orders/", OrdersListViev.as_view(), name='orders_list'),
    path("user-orders/<int:user_id>/", UserOrdersListView.as_view(), name='user_orders_list'),
    path("orders/<int:user_id>/export", user_orders_export, name='orders_export'),
    path("orders/create/", OrderCreateView.as_view(), name='create_order'),
    path("orders/<int:pk>/", OrdersDetailViev.as_view(), name='order_details'),
    path("orders/<int:pk>/update", OrderUpdateView.as_view(), name='order_update'),
    path("orders/<int:pk>/confirm_delete/", OrderDeleteView.as_view(), name='order_delete'),
    path("api/", include(routers.urls)),
]

mysite/requestdataapp/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.files.uploadedfile import InMemoryUploadedFile

class UserBioForm(forms.Form):
    name = forms.CharField(label="Имя", max_length=100)
    age = forms.IntegerField(label="Возраст", min_value=1, max_value=120)
    bio = forms.CharField(label="Биография", widget=forms.Textarea)

def validate_file_name(file: InMemoryUploadedFile) -> None:
    if file.name and "virus" in file.name:
        raise ValidationError("Имя файла не должно содержать 'Вирус'")

class UploadFileForm(forms.Form):
    file = forms.FileField(validators=[validate_file_name])

mysite/requestdataapp/views.py
import sys
from http.client import HTTPResponse
from django.core.files.storage import FileSystemStorage
from django.db.models.expressions import result
from django.http import HttpRequest
from django.shortcuts import render
from .forms import UserBioForm, UploadFileForm

def process_det_view(request: HttpRequest) -> HTTPResponse:
    a = request.GET.get("a", "")
    b = request.GET.get("b", "")
    result = a + b

    context = {
        "a": a,
        "b": b,
        "result": result,
    }
    return render(request, "requestdataapp/request-query-params.html", context=context)

def user_form(request: HttpRequest) -> HTTPResponse:
    context = {
        "form": UserBioForm(),
    }
    return render(request, "requestdataapp/user-bio-form.html", context=context)

def handel_file_uploap(request: HttpRequest) -> HTTPResponse:


    if request.method == "POST":
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            # myfile = request.FILES["myfile"]
            myfile = form.cleaned_data["file"]
            fs = FileSystemStorage()
            print(myfile.size)
            if myfile.size > 1048576:
                print('ERROR, file size is more than 1 MB', file=sys.stderr)
                return render(request, "requestdataapp/error-message.html")
            else:
                filename = fs.save(myfile.name, myfile)
                print("saved file", filename)
    else:
        form = UploadFileForm()
    context = {
        "form": form,
    }
    return render(request, "requestdataapp/file-upload.html", context=context)

mysite/requestdataapp/templates/requestdataapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %}
    </title>
</head>
<body>
{% block body %}

{% endblock %}

<br>
<div>
    HTTP User-Agent {{ request.user_agent }}
</div>
</body>
</html>

mysite/requestdataapp/templates/requestdataapp/basereq.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
      {% block title %}
       Base Title
      {% endblock %}
    </title>

    <style>

      * {
        font-family: 'Roboto', sans-serif;
      }

      html, body {
        color: white;
        background-color: #f6f7f9;
        margin: 0;
        padding: 0;
      }

      header {
        color: white;
        padding: 20px 0px;
        background-color: #271d3e;
      }

      header > div {
        display: flex;
        justify-content: space-between;
        align-items: center;
      }

      .head-container {
        max-width: 1000px;
        height: 100%;
        margin-left: auto;
        margin-right: auto;
      }

      .head-container a{
        text-decoration: none;
        color: rgb(226, 77, 147);
      }

      .block {
        width: 100%;
        display: flex;
      }

      .block a {
        text-decoration: none;
        color: rgb(168, 73, 117);
      }


      .left-contein {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: space-between;
        /* background-color: aqua; */
        height: 100vh;
        width: 250px;
        padding: 10px;
        background-color: #271d3e;
        
      }

      .main-contein {
        text-align: center;
        background-color: rgb(70, 58, 97);
        width: 100%;
        padding: 20px;
        border-top: 1px solid black;
        border-left: 1px solid black;
        /* background-image: url('C:/Users/mrnif/Pictures/фоны/main.png');
        background-size: contain;
        background-repeat: no-repeat;
        background-position: right center; */
      }

      .navigate {
        display: flex;
        flex-direction: column;
        align-items: center;
      }

    </style>
</head>



<body>
    
  <header>
    <div class="head-container">
        <a href="{% url 'shopapp:index' %}">shopapp</a>
        <a href="{% url 'myauth:login' %}">auth</a>
        <a href="{% url 'requestdataapp:get-vew' %}">requestdataapp</a>
        <a href="{% url 'home:home-page' %}">home</a>
        <a href="{% url 'myauth:logout' %}" style="color: red">Выход</a>
    </div>
  </header>

  <section class="block">
    <div class="left-contein">
      <div class="navigate">
      
        <h2 style="border: 1px solid black; 
        border-radius: 40px; 
        padding: 20px;
        background-color: #2d0d79;"
        >Навигация</h2>

        <div style="margin-top: 60px ;">
          <p><a href="{% url 'requestdataapp:get-vew' %}">vew</a></p>
          <p><a href="{% url 'requestdataapp:user-form' %}">форма пользователя</a></p>
          <p><a href="{% url 'requestdataapp:file-upload' %}">загрузка файла</a></p>
        </div>

      </div>

      <div class="detail">
        <div>
          {% now 'H:i" %}
        </div>
  
        <div>
          {% now 'l' as current_weekday %}
          Today is {{ current_weekday }}
        </div>
      </div>
      

    </div>

    <div class="main-contein">
      {% block body %}
      Base Body
      {% endblock %}
    </div>

  </section>

  <footer>

  </footer>

</body>
</html>

mysite/requestdataapp/templates/requestdataapp/error-message.html
{% extends 'requestdataapp/basereq.html' %}

{% block title %}
    ERROR
{% endblock %}

{% block body %}
    <h1>Ошибка! Файл больше 1 мегабайта</h1>
    <a href="">Вернуться назад</a>
{% endblock %}

mysite/requestdataapp/templates/requestdataapp/error-request.html
{% extends 'requestdataapp/basereq.html' %}

{% block title %}
    ERROR
{% endblock %}

{% block body %}
    <h1>Ошибка! Повторный запрос с вашего IP-адреса можно сделать через 10 секунд</h1>
    <a href="">Пожождите 10 секунд и вы сможете вернуться назад</a>
{% endblock %}

mysite/requestdataapp/templates/requestdataapp/file-upload.html
{% extends 'requestdataapp/basereq.html' %}

{% block title %}
    File upload
{% endblock %}

{% block body %}
    <h1>Upload file</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form.as_p }}

    <button type="submit">Upload</button>
    </form>
{% endblock %}

mysite/requestdataapp/templates/requestdataapp/request-query-params.html
{% extends 'requestdataapp/basereq.html' %}

{% block title %}
    Demo request params
{% endblock %}

{% block body %}
    <h1>Gooa afternoon, {% firstof request.GET.name 'User' %}</h1>

    <div>
        <pre>
            a = '{{ a }}'
            b = '{{ b }}'
            result = '{{ result }}'
        </pre>
    </div>
{% endblock %}

mysite/requestdataapp/templates/requestdataapp/user-bio-form.html
{% extends 'requestdataapp/basereq.html' %}

{% block title %}
    User bio
{% endblock %}

{% block body %}

    <h1>User form</h1>
    <div>
        <form method="post">

            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit">
                Submit
            </button>
        </form>
    </div>

    {% if request.POST %}
        <div>
            <h2>Previos form data</h2>
        <table>

            <tr>
                <td>Full name:</td>
                <td>{{ request.POST.name }}</td>
            </tr>

            <tr>
                <td>Age:</td>
                <td>{{ request.POST.age }}</td>
            </tr>

            <tr>
                <td>Bio:</td>
                <td>
                    <p>{{ request.POST.bio|linebreaks}}</p>
                </td>
            </tr>

        </table>
        </div>
    {% endif %}

{% endblock %}